version: 0.2

env:
  variables:
    TF_VERSION: "1.8.5"

phases:
  install:
    commands:
      - yum install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - terraform init
      - terraform fmt -check
      - terraform validate

  build:
    commands:
      - terraform plan -out=tfplan

artifacts:
  files:
    - '**/*'
